[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  CHROME_BIN = "/usr/bin/google-chrome-stable"
  CHROME_PATH = "/usr/bin/google-chrome-stable"
