[build]
  command = "npm run build"
  publish = "out"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
