[build]
  command = "npm run build && npm run export"
  publish = "out"  # Ensure this matches the directory where your static files are exported

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
